Task 7

In [ ]:
#Given dictionaries
dict1 = {'Harry':15, 'Draco':8, 'Nevil':19}
dict2 = {'Ginie':18, 'Luna': 14}

#Creating an empty dictionary
marks = {}

#Putting the items of the dictionaries in the empty dictionary using a loop
for i in dict1:
  marks[i] = dict1[i]
for j in dict2:
  marks[j] = dict2[j]

#Printing the new dictionary
print(marks)

{'Harry': 15, 'Draco': 8, 'Nevil': 19, 'Ginie': 18, 'Luna': 14}

Task 8

In [ ]:
#Prompting the user for a string that will be made into a dictionary
user = input().split(", ")

#Creating a dictionary from a string input
dict1 = {}
for i in user:
  key,value = i.split(":")
  dict1[key] = int(value)

#Calculating and printing the average of all the values in the dictionary
sum = 0
counter = 0
for key in dict1:
  sum += dict1[key]
  counter += 1
avg = sum/counter

print(f"Average is {int(avg)}.")

Jon:100, Dan:200, Rob:30, Ned:110
Average is 110.

Task 9

In [ ]:
#Given dictionary
exam_marks = {'Cierra Vega': 175, 'Alden Cantrell': 200, 'Kierra Gentry': 165, 'Pierre Cox': 190}

#Prompting the user for the threshold
threshold = int(input())

#Putting the eligible items in the new dictionary and printing
new_dict = {}
for key in exam_marks:
  if exam_marks[key] >= threshold:
    new_dict[key] = exam_marks[key]

print(new_dict)

170
{'Cierra Vega': 175, 'Alden Cantrell': 200, 'Pierre Cox': 190}

Task 10

In [ ]:
#Given dictionary
dict1 = {'sci fi': 5, 'mystery': 3, 'horror': 14, 'young_adult': 2, 'adventure':9}

#Finding and printing the largest number and genre
max = 0 #here max can be 0 because we can't sell a book negative times
genre = ""

for key in dict1:
  if dict1[key] > max:
    max = dict1[key]
    genre = key

print(f"The highest selling book genre is '{genre}' and the number of books sold are {max}.")

The highest selling book genre is 'horror' and the number of books sold are 14.

Task 11

In [ ]:
#Prompting the user for a string
string = input().lower()

#Finding out frequencies
dict1 = {}
for i in string:
  if 97 <= ord(i) <= 122: #To avoid blanks and quotations
    if i not in dict1:
      dict1[i] = 1
    elif i in dict1:
      dict1[i] = dict1[i]+1
print(dict1)

"Python programming is fun"
{'p': 2, 'y': 1, 't': 1, 'h': 1, 'o': 2, 'n': 3, 'r': 2, 'g': 2, 'a': 1, 'm': 2, 'i': 2, 's': 1, 'f': 1, 'u': 1}

Task 12

In [ ]:
#Given dictionary
dict_1 = {'A': [1, 2, 3], 'b': ['1', '2'], "c": [4, 5, 6, 7]}

#Counting characters in the lists and printing
counter = 0
for i in dict_1.values():
  list1 = i
  for j in list1:
    counter += 1

print(counter)

9

Task 13

In [ ]:
#Given dictionary
list_1 = [("a", 1), ("b", 2), ("a", 3), ("b", 1), ("a", 2), ("c", 1)]

#Converting the list to a dictionary
dict1 = {}
for i in list_1:
  key,value = i
  if key not in dict1:
    dict1[key] = [value]
  else:
    dict1[key].append(value)
print(dict1)

{'a': [1, 3, 2], 'b': [2, 1], 'c': [1]}