Task 1

In [ ]:
#Write your code here for subtasks 1-4.

class Student:

  ID = 0

  def __init__(self, name, department, age, cgpa):
    self.name = name
    self.department = department
    self.age = age
    self.cgpa = cgpa
    Student.ID += 1

  def showDetails(self):
    print(f"ID: {self.ID}\nName: {self.name}\nDepartment: {self.department}\nAge: {self.age}\nCGPA: {self.cgpa}")

  @classmethod
  def from_String(cls, info):
    name, department, age, cgpa = info.split("-")
    obj = cls(name, department, age, cgpa)
    return obj

s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

# Write the answer of subtask 5 here
print("The differences between class variables and instance variables are, class variables can be accessed and modified without instantiation while instance variables cannot. Also, class variables can store values that are constant accross all instances while instance variables can store different values for each object created.")
# Write the answer of subtask 6 here
print("The differences between class methods and instance methods are, we can call class methods without doing instantiation while we can only call instance methods after doing instantiation of the class. Class methods can only access and modify class variables and not instance variable while instance variables can access and modify both.")

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96
The differences between class variables and instance variables are, class variables can be accessed and modified without instantiation while instance variables cannot. Also, class variables can store values that are constant accross all instances while instance variables can store different values for each object created.
The differences between class methods and instance methods are, we can call class methods without doing instantiation while we can only call instance methods after doing instantiation of the class. Class methods can only access and modify class variables and not instance variable while instance variables can access and modify both.

Task 2

In [ ]:
class Passenger:

  count = 0

  def __init__(self, name):
    self.name = name
    Passenger.count += 1
    self.fare = 450

  def set_bag_weight(self, weight):
    if 21 < weight <= 50:
      self.fare += 50
    elif weight > 50:
      self.fare += 100

  def printDetail(self):
    print(f"Name: {self.name}\nBus Fare: {self.fare}")

print("Total Passenger:", Passenger.count)
p1 = Passenger("Jack")
p1.set_bag_weight(90)
p2 = Passenger("Carol")
p2.set_bag_weight(10)
p3 = Passenger("Mike")
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print("Total Passenger:", Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus Fare: 550
=========================
Name: Carol
Bus Fare: 450
=========================
Name: Mike
Bus Fare: 500
=========================
Total Passenger: 3

Task 3

In [ ]:
class Travel:
  count = 0
  def __init__(self, source, destination):
    self.source = source
    self.destination = destination
    self.time = 1
    Travel.count += 1

  def display_travel_info(self):
    return f"Source: {self.source}\nDestination:{self.destination}\nFlight Time:{self.time}:00"

  def set_time(self, time):
    self.time = time

  def set_destination(self, place):
    self.destination = place

  def set_source(self, place):
    self.source = place

print("No. of Traveller =", Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print("No. of Traveller =", Travel.count)

No. of Traveller = 0
=======================
Source: Dhaka
Destination:India
Flight Time:1:00
=======================
Source: Kuala Lampur
Destination:Dhaka
Flight Time:23:00
=======================
Source: Dhaka
Destination:Germany
Flight Time:15:00
=======================
Source: Malaysia
Destination:Canada
Flight Time:9:00
=======================
No. of Traveller = 4

Task 4

In [4]:
class NikeBangladesh:

  branch = []
  stock = {'Air Jordan':0, 'Cortez':0, 'Zoom Kobe':0}
  sold = 0

  def __init__(self, name):
    self.name = name
    self.local_stock = {'Air Jordan':0, 'Cortez':0, 'Zoom Kobe':0}
    self.local_sold = 0
    NikeBangladesh.branch.append(name)

  @classmethod
  def status(cls):
    print(f"Nike Bangladesh Status:\nBranches Opened: {cls.branch}\nCurrently Stocked\n{cls.stock}\nSold: {cls.sold}")

  def details(self):
    print(f"Nike {self.name} outlet:\nProducts Currently Stocked:\n{self.local_stock}\nSold: {self.local_sold}")

  def restockProducts(self, products):
    for key in products:
      NikeBangladesh.stock[key] += products[key]
      self.local_stock[key] += products[key]

  def productSold(self, products):
    for key in products:
      NikeBangladesh.stock[key] -= products[key]
      self.local_stock[key] -= products[key]
      NikeBangladesh.sold += products[key]
      self.local_sold += products[key]

print("xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
dhaka = NikeBangladesh("Dhaka Banani")
chittagong = NikeBangladesh("Chittagong GEC")
print("xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx")
dhaka.details()
print("xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx")
chittagong.details()
print("xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx")
dhaka.restockProducts(
{"Air Jordan":1200,"Cortez":200,"Zoom Kobe":200})
chittagong.restockProducts(
{"Air Jordan":1000,"Cortez":250,"Zoom Kobe":100})
print("xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
print("xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx")
dhaka.productSold({"Air Jordan":760,"Cortez":90})
chittagong.productSold({"Air Jordan":520,"Zoom Kobe":70})
print("xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx")
NikeBangladesh.status()

xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: []
Currently Stocked
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx
Nike Dhaka Banani outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx
Nike Chittagong GEC outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 2200, 'Cortez': 450, 'Zoom Kobe': 300}
Sold: 0
xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 920, 'Cortez': 360, 'Zoom Kobe': 230}
Sold: 1440

Task 5

In [ ]:
class Student:

  total_student = 0
  brac_student = 0
  other_student = 0

  def __init__(self, name, department, institution = 'BRAC University'):
    self.name = name
    self.department = department
    self.institution = institution
    Student.total_student += 1
    if institution == 'BRAC University':
      Student.brac_student += 1
    else:
      Student.other_student += 1

  @classmethod
  def printDetails(cls):
    print(f"Total Student(s): {cls.total_student}\nBRAC University Student(s): {cls.brac_student}\nOther Institution Student(s): {cls.other_student}")

  def individualDetail(self):
    print(f"Name: {self.name}\nDepartment: {self.department}\nInstitution: {self.institution}")

  @classmethod
  def createStudent(cls, name, department, institution = 'BRAC University'):
    obj = cls(name, department, institution)
    return obj

Student.printDetails()
print('#########################')

mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()

print('========================')

harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()

print('=========================')

levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s): 0
BRAC University Student(s): 0
Other Institution Student(s): 0
#########################
Name: Mikasa Ackerman
Department: CSE
Institution: BRAC University
------------------------------------------
Total Student(s): 1
BRAC University Student(s): 1
Other Institution Student(s): 0
========================
Name: Harry Potter
Department: Defence Against Dark Arts
Institution: Hogwarts School
-------------------------------------------
Total Student(s): 2
BRAC University Student(s): 1
Other Institution Student(s): 1
=========================
Name: Levi Ackerman
Department: CSE
Institution: BRAC University
--------------------------------------------
Total Student(s): 3
BRAC University Student(s): 2
Other Institution Student(s): 1

Task 6

In [ ]:
class SultansDine:

  branch = 0
  total_sell = 0
  branch_list = []

  def __init__(self, name):
    self.name = name
    self.branch_sell = 0
    SultansDine.branch += 1
    SultansDine.branch_list.append(self)

  @classmethod
  def details(cls):
    print(f"Total Number of branch(s): {cls.branch}\nTotal Sell: {cls.total_sell} Taka")
    for i in cls.branch_list:
      percentage = (i.branch_sell/cls.total_sell)*100
      print(f"Branch Name: {i.name}, Branch Sell: {i.branch_sell} Taka\nBranch consists of total sell's: {round(percentage,2)}%")

  def sellQuantity(self, quantity):
    if quantity < 10:
      self.branch_sell = quantity*300
    elif quantity < 20:
      self.branch_sell = quantity*350
    else:
      self.branch_sell = quantity*400
    SultansDine.total_sell += self.branch_sell

  def branchInformation(self):
    print(f"Branch Name: {self.name}\nBranch Sell: {self.branch_sell} Taka")

SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch Sell: 10000 Taka
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 100.0%
========================
Branch Name: Baily Road
Branch Sell: 5250 Taka
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 65.57%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700 Taka
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 55.71%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 29.25%
Branch Name: Gulshan, Branch Sell: 2700 Taka
Branch consists of total sell's: 15.04%